### ISSUE TITLE
Pipenv fails to install Black 19.10b0 with pytest-black

### ISSUE THREAD

**Issue by chrisgeru** [shopkeep/pytest-black#38]
Pipfile:
```
[dev-packages]
black = "==19.10b0"
pytest = "*"
pytest-black = "*"

[pipenv]
allow_prereleases = false
```
works for black 19.3b0 but fails for 19.10b0 with the following error:
```
ERROR: ERROR: Could not find a version that matches black==19.10b0,==19.3b0
Skipped pre-versions: 18.3a0, 18.3a0, 18.3a1, 18.3a1, 18.3a2, 18.3a2, 18.3a3, 18.3a3, 18.3a4, 18.3a4, 18.4a0, 18.4a0, 18.4a1, 18.4a1, 18.4a2, 18.4a2, 18.4a3, 18.4a3, 18.4a4, 18.4a4, 18.5b0, 18.5b0, 18.5b1, 18.5b1, 18.6b0, 18.6b0, 18.6b1, 18.6b1, 18.6b2, 18.6b2, 18.6b3, 18.6b3, 18.6b4, 18.6b4, 18.9b0, 18.9b0, 19.3b0, 19.3b0, 19.10b0, 19.10b0
There are incompatible versions in the resolved dependencies.
```

The issue, i believe, is on this line inside setup.py: https://github.com/shopkeep/pytest-black/blob/7335ce2a29e842d28a6d7a1ad2464d343dcc0cf7/setup.py#L29

**Comment by paddycarey** [comment]
I think this was fixed a while back, let me know if not!

**Comment by RoelvandenBerg** [comment]
This problem resurfaces for me with the following Pipfile (and pipenv, version 2018.11.26): 

```python
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
"black" = "==19.3b0"
"pytest-black" = "==0.3.9"
"pytest" = "==5.4.*"

[requires]
python_version = "3.8"

[pipenv]
allow_prereleases = false
```

**Comment by thomascobb** [comment]
This is also still a problem for me with the Pipfile posted above. It seems like flake8-black has a similar issue, but has solved it by removing the minimum requirement on black: https://github.com/peterjc/flake8-black/pull/22

Given that the minimum requirement on black is over a year old, would you consider doing the same for pytest-black?
